### ISSUE TITLE
how do you install?

### ISSUE THREAD

**Issue by bendnuts** [Lonami/pyndustric#40]
pip install . in the cloned repository is giving me a bunch of "UNKNOWN"s

**Comment by Lonami** [comment]
Honestly it's been a while since I did this. I think [`poetry`](https://python-poetry.org/) is capable of installing projects with a `pyproject.toml`. Or maybe there's simply no install step and the current usage is to clone the repository and just run the command indicated in the `README`. That might be it.

**Comment by bendnuts** [comment]
```
bendn@klunk$pyndustric[master !?] touch new.py
bendn@klunk$pyndustric[master !?] python -m pyndustric new.py
# reading n...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bendn/pyndustric/pyndustric/__main__.py", line 53, in <module>
    main()
  File "/home/bendn/pyndustric/pyndustric/__main__.py", line 32, in main
    with open(file, encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'n'
bendn@klunk$pyndustric[master !?] touch n
bendn@klunk$pyndustric[master !?] python -m pyndustric n
# reading n...
# compiling n...
set __pyc_sp 0
end

# compiled n with pyndustric 0.1 in 0.00s
```interesting... it doesnt very much like files that are in a folder other than the repository, or that have names longer than one character...

**Comment by Lonami** [comment]
That definitely sounds like a bug. Could you follow up with a new issue (or even a PR, it seems simple enough)?

**Comment by bendnuts** [comment]
maybe, ill look at the code

**Comment by bendnuts** [comment]
the issue seems to be that it attributes each letter to a seperate file, hence the for loop
